In [1]:
from sentence_transformers import CrossEncoder

model = CrossEncoder("Qwen/Qwen3-Reranker-4B")

/home/coene/.local/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'Could not load this library: /home/coene/.local/lib/python3.11/site-packages/torchvision/image.so'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

modules.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/325 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/14.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/362 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/32.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/214 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/9.71k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/741 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

Default prompt name is set to 'query'. This prompt will be applied to all inference calls, except if a `prompt` or `prompt_name` parameter is provided.

In [2]:
query = "What is the capital of China?"
documents = [
    "The capital of China is Beijing.",
    "Gravity is a force that attracts two bodies towards each other. It gives weight to physical objects and is responsible for the movement of planets around the sun.",
]

pairs = [(query, doc) for doc in documents]
scores = model.predict(pairs)
print(scores)
# [  6.4375 -14.375 ]

rankings = model.rank(query, documents)
print(rankings)

[  6.3125 -14.375 ]
[{'corpus_id': 0, 'score': 6.3125}, {'corpus_id': 1, 'score': -14.375}]

In [3]:
import pandas as pd

df = pd.read_csv("../data/3_gold/questions_v2_rrf_union.csv")

In [4]:
N = 10
for index, row in df.sample(n=N).iterrows():
    print(f"**** {index} ****")
    query = row['question']
    docs  = [
        row[f'abstract_{i}'] for i in range(1,6) 
    ]
    scores = model.rank(query, docs)
    for score in scores:
        print(f"Index: {score['corpus_id']}")
        print(f"Score: {score['score']:.4f}")
        print(f"Document: {docs[score['corpus_id']][:100]}...")
        print("-" * 100)
    print("*"*120
    )
    input("Enter para continuar")

**** 102 ****
Index: 3
Score: 0.7500
Document: To validate the second-by-second dynamics of turbines in field experiments, it is necessary to accur...
----------------------------------------------------------------------------------------------------
Index: 2
Score: -2.6875
Document: In this report, the evolution of PM2.5 concentration at Escuelas Aguirre monitoring station during t...
----------------------------------------------------------------------------------------------------
Index: 1
Score: -3.0000
Document: We propose an analytical model based on the solution of the magnetohydrodynamics (MHD) equations for...
----------------------------------------------------------------------------------------------------
Index: 0
Score: -3.1875
Document: Wind, as a clean and sustainable source of energy, has witnessed significant growth in recent years....
----------------------------------------------------------------------------------------------------
Index: 4
Score: -4.3125
Document: Global characteristics of the small-scale gravity wave (GW) field in the Martian atmosphere obtained...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************
**** 24 ****
Index: 2
Score: 4.0625
Document: Traditional models of climate change use complex systems of coupled equations to simulate physical p...
----------------------------------------------------------------------------------------------------
Index: 4
Score: 2.5000
Document: The Earth, like other planets with a relatively thick atmosphere, is not locally in radiative equili...
----------------------------------------------------------------------------------------------------
Index: 0
Score: 1.2500
Document: Deep-learning-based climate downscaling aims to learn relationships from historical low-resolution (...
----------------------------------------------------------------------------------------------------
Index: 1
Score: -3.8750
Document: Climate change, amplified in the far north, has led to rapid sea ice decline in recent years. In the...
----------------------------------------------------------------------------------------------------
Index: 3
Score: -5.5625
Document: Earth's atmosphere is in a state far from thermodynamic equilibrium. For example, the large scale eq...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************
**** 1 ****
Index: 2
Score: 5.6250
Document: With the rapid amassing of spatial-temporal (ST) ocean data, many spatial-temporal data mining (STDM...
----------------------------------------------------------------------------------------------------
Index: 1
Score: -0.1250
Document: The field of weather and climate science is at a pivotal moment, defined by the dual forces of unpre...
----------------------------------------------------------------------------------------------------
Index: 3
Score: -0.9375
Document: The Nobel Prize in Physics 2021 was awarded to Syukuro Manabe, Klaus Hasselmann, and Giorgio Parisi ...
----------------------------------------------------------------------------------------------------
Index: 0
Score: -8.6875
Document: While extensive guidance exists for ensuring the reproducibility of one's own study, there is little...
----------------------------------------------------------------------------------------------------
Index: 4
Score: -12.8125
Document: This study delves into the predictability of atmospheric blocking, zonal, and transition patterns ut...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************
**** 274 ****
Index: 2
Score: 1.6250
Document: This paper is a continuation of a series of works, devoted to various aspects of the June 30, 1908 T...
----------------------------------------------------------------------------------------------------
Index: 0
Score: 0.6250
Document: The atmospheric pressure fluctuations on Mars induce an elastic response in the ground that creates ...
----------------------------------------------------------------------------------------------------
Index: 3
Score: -2.0000
Document: Collisional charging is one potential initial step in generating lightning. In this work, we study t...
----------------------------------------------------------------------------------------------------
Index: 4
Score: -4.4375
Document: This paper aims at contributing to the coastal environmental management by developing a new trophic ...
----------------------------------------------------------------------------------------------------
Index: 1
Score: -6.5312
Document: Arrays of acoustic receivers are an integral part of present and potential future Cherenkov neutrino...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************
**** 353 ****
Index: 0
Score: 2.8750
Document: This study assesses global offshore wind energy resources, wake-induced losses, array layout optimis...
----------------------------------------------------------------------------------------------------
Index: 1
Score: 1.1250
Document:   The International Polar Year commences in 2007. We offer a macroproject plan to generate a large a...
----------------------------------------------------------------------------------------------------
Index: 4
Score: 0.1250
Document: Rapid deployment of offshore wind is expected within the coming decades to help meet climate goals. ...
----------------------------------------------------------------------------------------------------
Index: 2
Score: 0.0000
Document: Because of their intense incident stellar irradiation and likely tidally locked spin states, hot Jup...
----------------------------------------------------------------------------------------------------
Index: 3
Score: -8.6250
Document: The development of low-level mesocyclones in supercell thunderstorms has often been explained via th...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************
**** 302 ****
Index: 3
Score: 6.0625
Document: Coupled data assimilation (CDA) distinctively appears as a main concern in numerical weather and cli...
----------------------------------------------------------------------------------------------------
Index: 4
Score: 5.2500
Document: We study a simplified coupled atmosphere-ocean model using the formalism of covariant Lyapunov vecto...
----------------------------------------------------------------------------------------------------
Index: 0
Score: 4.6875
Document: Data assimilation (DA) aims at optimally merging observational data and model outputs to create a co...
----------------------------------------------------------------------------------------------------
Index: 1
Score: -2.0000
Document: Baroclinic instability is a fundamental mechanism driving atmospheric dynamics. In this work, we rev...
----------------------------------------------------------------------------------------------------
Index: 2
Score: -2.1875
Document: We show that the choice of the norm has a great impact on the construction of ensembles of bred vect...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************
**** 257 ****
Index: 4
Score: 4.2500
Document: Irregular, unidirectional surface water waves incident on model ice in an ice tank are used as a phy...
----------------------------------------------------------------------------------------------------
Index: 0
Score: 2.0000
Document: The Marginal Ice Zone is a highly dynamic region where the atmosphere, ocean, waves and sea ice meet...
----------------------------------------------------------------------------------------------------
Index: 3
Score: -0.8750
Document: We perform an out-of-distribution analysis of ~12,000,000 semi-independent 128x128 pixel^2 SST regio...
----------------------------------------------------------------------------------------------------
Index: 1
Score: -1.0000
Document: A novel split-explicit (SE) external mode solver for the Finite volumE Sea ice-Ocean Model (FESOM2) ...
----------------------------------------------------------------------------------------------------
Index: 2
Score: -4.1875
Document: The Bay of Bengal (BoB) is a high recipient of freshwater flux from rivers and precipitation, making...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************
**** 401 ****
Index: 1
Score: 3.1875
Document: Machine learning (ML) has emerged as a novel tool for generating large-scale land surface data in re...
----------------------------------------------------------------------------------------------------
Index: 4
Score: -1.2500
Document: Urbanization is advancing rapidly, covering less than 2% of Earth's surface yet profoundly influenci...
----------------------------------------------------------------------------------------------------
Index: 0
Score: -3.6875
Document: Sparse meteorological forecasting is indispensable for fine-grained weather forecasting and deserves...
----------------------------------------------------------------------------------------------------
Index: 2
Score: -4.1250
Document: We present the CIENS dataset, which contains ensemble weather forecasts from the operational convect...
----------------------------------------------------------------------------------------------------
Index: 3
Score: -5.9688
Document: Satellite-derived measurements are negatively impacted by cloud cover and surface reflectivity. Thes...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************
**** 297 ****
Index: 0
Score: 4.1875
Document: In this paper, we analyze the predictability of the ocean currents using deep learning. More specifi...
----------------------------------------------------------------------------------------------------
Index: 2
Score: 1.3750
Document: Gyres are central features of large-scale ocean circulation and are involved in transporting tracers...
----------------------------------------------------------------------------------------------------
Index: 3
Score: -1.5625
Document: Inertial particles (i.e. with mass and of finite size) immersed in a fluid in motion are unable to a...
----------------------------------------------------------------------------------------------------
Index: 1
Score: -2.6875
Document: Turbulence closure models are essential for solving the equations of motion in realistic systems, wh...
----------------------------------------------------------------------------------------------------
Index: 4
Score: -6.2500
Document: The results of field work on drift ice during wave propagation are analyzed and presented. The field...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************
**** 299 ****
Index: 4
Score: 2.6875
Document: The accelerated change in our planet due to human activities has led to grand societal challenges in...
----------------------------------------------------------------------------------------------------
Index: 2
Score: 0.6250
Document: The increasing size and severity of wildfires across the western United States have generated danger...
----------------------------------------------------------------------------------------------------
Index: 3
Score: -1.3125
Document: We study the mitigation of climate tipping point transitions using an energy balance model. The evol...
----------------------------------------------------------------------------------------------------
Index: 0
Score: -2.0000
Document: The resilience of electric power grids is threatened by natural hazards. Climate-related hazards are...
----------------------------------------------------------------------------------------------------
Index: 1
Score: -6.0938
Document: Upgrading effluent standards of wastewater treatment plants (WWTPs) and repairing sewerage systems l...
----------------------------------------------------------------------------------------------------
************************************************************************************************************************

In [5]:
if "max_score" not in df.columns:
    df["max_score"] = None
if "min_score" not in df.columns:
    df["min_score"] = None

In [17]:
import numpy as np

def tang_hiperbolica(val:float)->float:
    return np.tanh(0.2 * val)

In [18]:
for index, row in df.iterrows():
    print(f"**** {index} ****")
    query = row["question"]
    docs = [row[f"abstract_{i}"] for i in range(1, 6)]

    scores = model.rank(query, docs)

    # Extraer los puntajes
    lista_scores = [tang_hiperbolica(s["score"]) for s in scores]

    # Guardar los valores directamente en la fila del DataFrame usando .at
    df.at[index, "max_score"] = max(lista_scores)
    df.at[index, "min_score"] = min(lista_scores)

**** 0 ****
**** 1 ****
**** 2 ****
**** 3 ****
**** 4 ****
**** 5 ****
**** 6 ****
**** 7 ****
**** 8 ****
**** 9 ****
**** 10 ****
**** 11 ****
**** 12 ****
**** 13 ****
**** 14 ****
**** 15 ****
**** 16 ****
**** 17 ****
**** 18 ****
**** 19 ****
**** 20 ****
**** 21 ****
**** 22 ****
**** 23 ****
**** 24 ****
**** 25 ****
**** 26 ****
**** 27 ****
**** 28 ****
**** 29 ****
**** 30 ****
**** 31 ****
**** 32 ****
**** 33 ****
**** 34 ****
**** 35 ****
**** 36 ****
**** 37 ****
**** 38 ****
**** 39 ****
**** 40 ****
**** 41 ****
**** 42 ****
**** 43 ****
**** 44 ****
**** 45 ****
**** 46 ****
**** 47 ****
**** 48 ****
**** 49 ****
**** 50 ****
**** 51 ****
**** 52 ****
**** 53 ****
**** 54 ****
**** 55 ****
**** 56 ****
**** 57 ****
**** 58 ****
**** 59 ****
**** 60 ****
**** 61 ****
**** 62 ****
**** 63 ****
**** 64 ****
**** 65 ****
**** 66 ****
**** 67 ****
**** 68 ****
**** 69 ****
**** 70 ****
**** 71 ****
**** 72 ****
**** 73 ****
**** 74 ****
**** 75 ****
**** 76 ****
**** 77 ****
**** 78 ****
**** 79 ****
**** 80 ****
**** 81 ****
**** 82 ****
**** 83 ****
**** 84 ****
**** 85 ****
**** 86 ****
**** 87 ****
**** 88 ****
**** 89 ****
**** 90 ****
**** 91 ****
**** 92 ****
**** 93 ****
**** 94 ****
**** 95 ****
**** 96 ****
**** 97 ****
**** 98 ****
**** 99 ****
**** 100 ****
**** 101 ****
**** 102 ****
**** 103 ****
**** 104 ****
**** 105 ****
**** 106 ****
**** 107 ****
**** 108 ****
**** 109 ****
**** 110 ****
**** 111 ****
**** 112 ****
**** 113 ****
**** 114 ****
**** 115 ****
**** 116 ****
**** 117 ****
**** 118 ****
**** 119 ****
**** 120 ****
**** 121 ****
**** 122 ****
**** 123 ****
**** 124 ****
**** 125 ****
**** 126 ****
**** 127 ****
**** 128 ****
**** 129 ****
**** 130 ****
**** 131 ****
**** 132 ****
**** 133 ****
**** 134 ****
**** 135 ****
**** 136 ****
**** 137 ****
**** 138 ****
**** 139 ****
**** 140 ****
**** 141 ****
**** 142 ****
**** 143 ****
**** 144 ****
**** 145 ****
**** 146 ****
**** 147 ****
**** 148 ****
**** 149 ****
**** 150 ****
**** 151 ****
**** 152 ****
**** 153 ****
**** 154 ****
**** 155 ****
**** 156 ****
**** 157 ****
**** 158 ****
**** 159 ****
**** 160 ****
**** 161 ****
**** 162 ****
**** 163 ****
**** 164 ****
**** 165 ****
**** 166 ****
**** 167 ****
**** 168 ****
**** 169 ****
**** 170 ****
**** 171 ****
**** 172 ****
**** 173 ****
**** 174 ****
**** 175 ****
**** 176 ****
**** 177 ****
**** 178 ****
**** 179 ****
**** 180 ****
**** 181 ****
**** 182 ****
**** 183 ****
**** 184 ****
**** 185 ****
**** 186 ****
**** 187 ****
**** 188 ****
**** 189 ****
**** 190 ****
**** 191 ****
**** 192 ****
**** 193 ****
**** 194 ****
**** 195 ****
**** 196 ****
**** 197 ****
**** 198 ****
**** 199 ****
**** 200 ****
**** 201 ****
**** 202 ****
**** 203 ****
**** 204 ****
**** 205 ****
**** 206 ****
**** 207 ****
**** 208 ****
**** 209 ****
**** 210 ****
**** 211 ****
**** 212 ****
**** 213 ****
**** 214 ****
**** 215 ****
**** 216 ****
**** 217 ****
**** 218 ****
**** 219 ****
**** 220 ****
**** 221 ****
**** 222 ****
**** 223 ****
**** 224 ****
**** 225 ****
**** 226 ****
**** 227 ****
**** 228 ****
**** 229 ****
**** 230 ****
**** 231 ****
**** 232 ****
**** 233 ****
**** 234 ****
**** 235 ****
**** 236 ****
**** 237 ****
**** 238 ****
**** 239 ****
**** 240 ****
**** 241 ****
**** 242 ****
**** 243 ****
**** 244 ****
**** 245 ****
**** 246 ****
**** 247 ****
**** 248 ****
**** 249 ****
**** 250 ****
**** 251 ****
**** 252 ****
**** 253 ****
**** 254 ****
**** 255 ****
**** 256 ****
**** 257 ****
**** 258 ****
**** 259 ****
**** 260 ****
**** 261 ****
**** 262 ****
**** 263 ****
**** 264 ****
**** 265 ****
**** 266 ****
**** 267 ****
**** 268 ****
**** 269 ****
**** 270 ****
**** 271 ****
**** 272 ****
**** 273 ****
**** 274 ****
**** 275 ****
**** 276 ****
**** 277 ****
**** 278 ****
**** 279 ****
**** 280 ****
**** 281 ****
**** 282 ****
**** 283 ****
**** 284 ****
**** 285 ****
**** 286 ****
**** 287 ****
**** 288 ****
**** 289 ****
**** 290 ****
**** 291 ****
**** 292 ****
**** 293 ****
**** 294 ****
**** 295 ****
**** 296 ****
**** 297 ****
**** 298 ****
**** 299 ****
**** 300 ****
**** 301 ****
**** 302 ****
**** 303 ****
**** 304 ****
**** 305 ****
**** 306 ****
**** 307 ****
**** 308 ****
**** 309 ****
**** 310 ****
**** 311 ****
**** 312 ****
**** 313 ****
**** 314 ****
**** 315 ****
**** 316 ****
**** 317 ****
**** 318 ****
**** 319 ****
**** 320 ****
**** 321 ****
**** 322 ****
**** 323 ****
**** 324 ****
**** 325 ****
**** 326 ****
**** 327 ****
**** 328 ****
**** 329 ****
**** 330 ****
**** 331 ****
**** 332 ****
**** 333 ****
**** 334 ****
**** 335 ****
**** 336 ****
**** 337 ****
**** 338 ****
**** 339 ****
**** 340 ****
**** 341 ****
**** 342 ****
**** 343 ****
**** 344 ****
**** 345 ****
**** 346 ****
**** 347 ****
**** 348 ****
**** 349 ****
**** 350 ****
**** 351 ****
**** 352 ****
**** 353 ****
**** 354 ****
**** 355 ****
**** 356 ****
**** 357 ****
**** 358 ****
**** 359 ****
**** 360 ****
**** 361 ****
**** 362 ****
**** 363 ****
**** 364 ****
**** 365 ****
**** 366 ****
**** 367 ****
**** 368 ****
**** 369 ****
**** 370 ****
**** 371 ****
**** 372 ****
**** 373 ****
**** 374 ****
**** 375 ****
**** 376 ****
**** 377 ****
**** 378 ****
**** 379 ****
**** 380 ****
**** 381 ****
**** 382 ****
**** 383 ****
**** 384 ****
**** 385 ****
**** 386 ****
**** 387 ****
**** 388 ****
**** 389 ****
**** 390 ****
**** 391 ****
**** 392 ****
**** 393 ****
**** 394 ****
**** 395 ****
**** 396 ****
**** 397 ****
**** 398 ****
**** 399 ****
**** 400 ****
**** 401 ****
**** 402 ****
**** 403 ****
**** 404 ****
**** 405 ****
**** 406 ****
**** 407 ****
**** 408 ****
**** 409 ****
**** 410 ****
**** 411 ****
**** 412 ****
**** 413 ****
**** 414 ****
**** 415 ****
**** 416 ****
**** 417 ****
**** 418 ****
**** 419 ****
**** 420 ****
**** 421 ****
**** 422 ****
**** 423 ****
**** 424 ****
**** 425 ****
**** 426 ****
**** 427 ****
**** 428 ****
**** 429 ****
**** 430 ****
**** 431 ****
**** 432 ****
**** 433 ****
**** 434 ****
**** 435 ****
**** 436 ****
**** 437 ****
**** 438 ****
**** 439 ****
**** 440 ****
**** 441 ****
**** 442 ****
**** 443 ****
**** 444 ****
**** 445 ****
**** 446 ****
**** 447 ****
**** 448 ****
**** 449 ****
**** 450 ****
**** 451 ****
**** 452 ****
**** 453 ****
**** 454 ****
**** 455 ****
**** 456 ****
**** 457 ****
**** 458 ****
**** 459 ****
**** 460 ****
**** 461 ****
**** 462 ****
**** 463 ****
**** 464 ****
**** 465 ****
**** 466 ****
**** 467 ****
**** 468 ****
**** 469 ****
**** 470 ****
**** 471 ****
**** 472 ****
**** 473 ****
**** 474 ****
**** 475 ****
**** 476 ****
**** 477 ****
**** 478 ****
**** 479 ****
**** 480 ****
**** 481 ****
**** 482 ****
**** 483 ****
**** 484 ****
**** 485 ****
**** 486 ****
**** 487 ****
**** 488 ****
**** 489 ****
**** 490 ****
**** 491 ****
**** 492 ****
**** 493 ****
**** 494 ****
**** 495 ****
**** 496 ****
**** 497 ****
**** 498 ****
**** 499 ****

In [20]:
df['max_score'] = df['max_score'].astype(float)
df['min_score'] = df['min_score'].astype(float)

df.describe()

,Unnamed: 0,doc_id_1,doc_id_2,doc_id_3,doc_id_4,doc_id_5,qwen_res,gemma_res,rrf_res,rrf_mrr,union_res,max_score,min_score
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000
mean,249.500000,4032.966000,4146.206000,4156.740000,4161.346000,4263.376000,0.361600,0.328000,0.36080,0.384082,0.424800,0.572743,-0.713859
std,144.481833,2442.211788,2414.149222,2461.061102,2433.835404,2392.740464,0.251897,0.263048,0.25992,0.380427,0.268643,0.302718,0.252276
min,0.000000,3.000000,6.000000,0.000000,10.000000,8.000000,0.000000,0.000000,0.00000,0.000000,0.000000,-0.462117,-0.996844
25%,124.750000,2048.750000,2033.250000,2028.000000,2114.500000,2146.250000,0.200000,0.200000,0.20000,0.076900,0.200000,0.429564,-0.896922
50%,249.500000,3932.000000,4247.500000,4409.500000,4235.000000,4436.000000,0.400000,0.200000,0.40000,0.250000,0.400000,0.646187,-0.781806
75%,374.250000,6177.000000,6226.750000,6105.000000,6215.500000,6322.750000,0.600000,0.600000,0.60000,0.500000,0.600000,0.809301,-0.580025
max,499.000000,8433.000000,8404.000000,8368.000000,8427.000000,8440.000000,1.000000,1.000000,1.00000,1.000000,1.000000,0.969715,0.703906

In [21]:
df_specific_questions = pd.read_csv('../data/3_gold/eval_retrieval_qwen_kw.csv')
df_dataset = pd.read_csv('../data/1_raw/dataset.csv')

In [ ]:
resultados = []
for index, row in df_specific_questions.sample(n=500).iterrows():
    query = row['question']
    row_doc = df_dataset.loc[df_dataset['doc_id'] == row['doc_id']]
    abstract = row_doc['abstract'].values[0]

    scores = model.rank(query, [abstract])
    resultados.append(
        {
            "doc_id": row['doc_id'],
            "question": query,
            "abstract": abstract,
            "score": tang_hiperbolica(scores[0]['score']),
        }
    )

df_resultados = pd.DataFrame(resultados)
df_resultados

,doc_id,question,abstract,score
0,5467,Which specific geographical area was found to ...,Floating marine debris represent a threat to m...,0.970452
1,116,What provides the additional flow-field densit...,Hydrodynamic shielding is a theoretically well...,0.966583
2,4280,What effect does fragmentation have on the tot...,Field studies have shown that plastic fragment...,0.975137
3,801,Which specific timescales do both the hybrid m...,Physics-based atmosphere-land models with pres...,0.971171
4,4213,What happens to the temperature if the CO2 con...,We study the mitigation of climate tipping poi...,0.964028
...,...,...,...,...
495,6519,With which parameter is the sunspot number (SS...,We use Indian temperature data of more than 10...,0.954045
496,6879,At what distance was no evidence for azimuthal...,Numerical solutions are given for a parabolic ...,0.959335
497,5959,What is the median radius of the lognormal siz...,First results of multi-wavelength measurements...,0.941376
498,2865,What was the correlation value between the NPP...,Due to global warming and its detrimental effe...,0.921669
499,5679,What happens when shear and stratification are...,The large-scale structures in the ocean and th...,0.964900

In [25]:
df_resultados_f = df_resultados[df_resultados['score']>0.50]
df_resultados_f.describe()

            doc_id       score
count   492.000000  492.000000
mean   4244.058943    0.944363
std    2267.364959    0.062232
min      44.000000    0.500520
25%    2319.500000    0.948085
50%    4250.500000    0.961749
75%    6019.750000    0.968187
max    8406.000000    0.979598